# Replace with respective API autodiscoveryID
api:
  autodiscoveryID: "00000000"
  
# Listener configuration
https:
  host: "0.0.0.0"
  port: "8082"
  
# Global Party Process API configuration
global-party-prc-api:
  # Replace with respective application hostname
  host: "${global.cloudhub.appPrefix}global-party-prc-api-v1-qa.ca-c1.cloudhub.io"
  port: "443"
  base-path: "/api"
  ping-path: "/ping"
  getPartyRolesExternalIds: "/partyRoles/{partyRoleId}/externalIds"
  getPartyExternalIds: "/parties/{partyId}/externalIds"
  response-timeout: "60000"
  connection-idle-timeout: "3000"
  http-frequency: "5000"
  http-reconnection-attempts: "2"

# Address Validation System API configuration  
address-validation-sys-api:
  # Replace with respective application hostname
  host: "address-validation-sys-api-v1-qa.us-e1.cloudhub.io"
  port: "443"
  response-timeout: "60000"
  connection-idle-timeout: "3000"
  http-frequency: "5000"
  http-reconnection-attempts: "2"
  base-path: "/api"
  ping-path: "/ping"
  name: "FINS Address Validation System API"
